### ISSUE TITLE
DCF support

### ISSUE THREAD

**Issue by ryanpdx** [oresat/CANopen-monitor#53]
CANopen monitor should support DCF files too.

**Comment by ryanpdx** [comment]
Example dcf:  [generic_OD.txt](https://github.com/oresat/CANopen-monitor/files/6178122/generic_OD.txt)
**Note:** to attach this to a GitHub comment it is a `.txt` file. Noramally it would be a `.dcf` file

**Comment by Boneill3** [comment]
The only issue I had when parsing this file was that there is an empty line as the last line in the file, besides that the parser seems to be working just as well as with the eds file.

**Comment by ryanpdx** [comment]
Are you getting node id from index 0x2101?

**Comment by ryanpdx** [comment]
That index is added by CANopenNode by default and is not apart of the CANopen specs.

**Comment by ryanpdx** [comment]
I realize i forgot to set the node id and device name in in that dcf. It is set in [generic_OD.txt](https://github.com/oresat/CANopen-monitor/files/6192205/generic_OD.txt)

**Comment by Boneill3** [comment]
I noticed that nodeid here is 10, should that be 0x10? Or should decimal or hex be acceptable values?

**Comment by ryanpdx** [comment]
I know that one is decimal, i don't know if it can be hex.

**Comment by ryanpdx** [comment]
From eds/dcf specs:
"_Integer  numbers  shall  be  written  as  decimal  numbers,  hexadecimal  numbers  or  octal  numbers.  Hexadecimal numbers are preceded by 0x. Octal numbers shall start with a leading 0 (not followed by x)._"
