### ISSUE TITLE
ECSS time

### ISSUE THREAD

**Issue by ryanpdx** [oresat/CANopen-monitor#57]
Add support for ECSS time standards from the *ECSS CANBus extension protocol* specs. OreSat uses the `SCET` standard instead of the CANopen TIME standard. 
  
There is no standardize epoch. The recommended epoch is GPS time (January 5th 1980), on OreSat the epoch used is the Unix time stamp (January 1st 1970). So this probably needs to be a setting.

https://ecss.nl/standard/ecss-e-st-50-15c-space-engineering-canbus-extension-protocol-1-may-2015/

**Comment by dmitri-mcguckin** [comment]
The default timestamp for a CAN Date object is January 1st 1984, no?

**Comment by ryanpdx** [comment]
Yep, TIME_OF_DAY object epoch is January 1, 1984.

**Comment by ryanpdx** [comment]
[ECSS-CANBus-extension-protocol.pdf](https://github.com/oresat/CANopen-monitor/files/6534800/ECSS-CANBus-extension-protocol.pdf)
