### ISSUE TITLE
Change "Age:" to 1 second resolution

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/CANopen-monitor#64]
There's no reason to have < 1 second resolution on "Age", it just takes up space. Please remove all decimal points, kthx!

**Comment by dmitri-mcguckin** [comment]
This is tied to an unreported bug where the Message Table renderer isn't respecting callables, which is a bug that needs to be fixed first.

Will update this FR once the issue has been made.

**Comment by dmitri-mcguckin** [comment]
Need to resolve Issue #66 first.
