### ISSUE TITLE
Star Tracker dcf not working

### ISSUE THREAD

**Issue by ryanpdx** [oresat/CANopen-monitor#74]
**Describe the bug**
The star tracker is showing up as 0x30 in the display, even though canopen-monitor has its dcf in it's cache.

**To Reproduce**
- Start the star tracker on MDC.

**Expected behavior**
It should printing `Star Tracker` not `0x30`

**Environment (please complete the following information):**
MDC

**Additional context**
If i had to guess the canopen-monitor is assuming that the `NodeId` under `[DeviceComissioning]` is in hex, when it really is a decimal.

**Comment by Boneill3** [comment]
Is it always in decimal?

**Comment by ryanpdx** [comment]
If it has `0x` it's hex. If it doesn't have `0x`, it's a decimal.
